### ISSUE TITLE
[OP has an opinion that doesn't quite know how to articulate well]

### ISSUE THREAD

**Issue by soggie** [galambalazs/smoothscroll-for-websites#100]
Guys, there're literally countless different mice on the market, each with their own scrolling settings, and then you have touchscreens, and other pointer devices. Literal millions of different permutations of how scrolling works, and more often than not you can control the scrolling speed on the devices themselves, or the drivers they come with. Failing that, your OS will be able to offer some sort of settings to change it.

So why in the bloody hell does this need to be implemented on a website that overrides all these settings? Smooth scrolling to an anchor point I can understand; changing the scrolling speed of the mousewheel? Why??? The websites that I visit are all worse off because of this. So much so that I had to hunt around for chrome extensions just to disable this bullshit.

**Comment by kubiqsk** [comment]
You must be an Apple user, am I right? Because there is no smooth scroll on Windows...
and you're probably using that weird device called Magic mouse (?)

On many websites you can find some scroll-based-animations and as a webdeveloper I want it to be smooth...
also you need different scroll speed on websites with huge titles and images and different on websites with lot of text...
so I think **this is great UX enhancement**

P.S.: That's why I also created WP plugin with this script and thanks to me you can find this script on over 40 000 websites 😈
You're welcome 🤣 😘

**Comment by gblazex** [comment]
@soggie can you mention a website that is broken for you?

By default this script ignores changing scrolling for all high-precision devices. It only affects classical mouse wheels that turn and click into position.

Also the default scrolling step size should match your OS default. The only place you can run into issues should be sites stuck on old versions of this library.

@kubiqsk not quite, there is no smooth scrolling on Macs either. All third party mouses with classical mouse wheels have horrible scrolling by default.

**Comment by soggie** [comment]
@kubiqsk I'm using ubuntu with a pretty typical gaming mouse, a normal logitech mouse, and touchpad. None of which works properly with your plugin, nor does it do with any smoothscroll libraries out there. @gblazex If you need a reference on how bad it can be, here's a website using your library (bundled as part of a wordpress theme): https://mangafresh.com

**Comment by kubiqsk** [comment]
That website works pretty well for me
I tested touchpad, touchscreen and also mouse and everything is ok
Maybe there is a problem with your mouse configuration or mouse itself... try to use default settings (like 99% of people have)
🤷‍♂️
