### ISSUE TITLE
After passing the url, the plugin does not respond

### ISSUE THREAD

**Issue by waller-adv** [galambalazs/smoothscroll-for-websites#106]
Before changing the URL of the site everything worked fine
After moving to the new address and exiting a development environment
The plugin is not responding

**URL website new**
https://ganey-ahuza.co.il/

**Comment by kubiqsk** [comment]
@waller-adv please use the plugin suport forum
https://wordpress.org/support/plugin/mousewheel-smooth-scroll/
your website is not properly migrated, take a look on console errors.
Also try to deactivate the plugin and activate it back, or try to resave its settings.

**Comment by waller-adv** [comment]
I found the error
It tells me that the problem is because this add-on has an http address

The website has https

In which file do I update the address with an SSL certificate

**Comment by kubiqsk** [comment]
WordPress support forum please! Not here.
Again - your website is not properly migrated.
Yes, that means you have some http:// somewhere instead of https:// it can be in database, in cache or other generated files...
You can also have some old URLs somewhere maybe...
You need to read a few articles to solve this - just use google, or hire some developer who will fix this for you.
This has nothing to do with this library, or with the WP plugin itself.
Your website was not properly migrated and this is a wrong place to find a help for such a problem.
