### ISSUE TITLE
Disabled Scrolling When Chrome Zoom < 100%

### ISSUE THREAD

**Issue by bitwisecreative** [galambalazs/smoothscroll-for-websites#3]
Using Chrome 44

If I set the browser zoom to 90% and refresh the page, scrolling doesn't work. If I then set it back to 100% and refresh the page, scrolling works again. This seems to only occur for zoom < 100%.

**Comment by gblazex** [comment]
I'll look into this. Thanks!

**Comment by bitwisecreative** [comment]
I looked into this a bit. When zoomed out in Chrome, it doesn't use `scrollWindow` anymore, it switches to `scrollTop`. Then, the scroll elem becomes `html` (instead of `body`). Then, I noticed the `html` elem doesn't seem to respond to `scrollTop` in Chrome (?). Here's the temporary patch I'm using (in `step` function):

``` javascript
        // scroll left and top
        if (scrollWindow) {
            window.scrollBy(scrollX, scrollY);
        }
        else {
            // Chrome -zoom scroll patch
            if (navigator.userAgent.toLowerCase().indexOf('chrom') > -1) {
                elem = document.body;
            }
            if (scrollX) elem.scrollLeft += scrollX;
            if (scrollY) elem.scrollTop  += scrollY;
        }
```

**Comment by gblazex** [comment]
Unfortunately it's a little more involved than that. The `else` case is for all other overflowing elements. You can't assume it to be the `body`.

The answer will be some changes to `overflowingAncestor()` to account for the zoom level, and then it will return the `body` even when at 90%, which will make `scrollWindow` true, which will make the `if` case to run.

**Comment by bitwisecreative** [comment]
I figured it would be a bit more complicated. I saw all the overflow logic but didn't spend enough time to _learn_ it. I at least wanted to share what I found (which seems to be working well for my project, for now). Thank you very much for looking into this, and for the project. It's awesome :)

**Comment by gblazex** [comment]
Yes it's good as a quick fix for you if you have no overflowing elements (elements that can scroll other than body), but if I pushed your fix to the repo it'd break a lot of sites.

Thanks for finding where the problem is.

I'll need to spend more time to fix this.

**Comment by gblazex** [comment]
Seems to work with the extension version: https://github.com/galambalazs/smoothscroll

So the fix should focus on the differences between the two codebases.

**Comment by pc035860** [comment]
Since the extension version is just for Chrome, the `getScrollRoot()` function simply returns `document.body`.
https://github.com/galambalazs/smoothscroll/blob/master/src/sscr.js#L687

And for the website version of `getScrollRoot()`, the result would be `document.documentElement` in Chrome when zoom level < 100%.

Changing  https://github.com/galambalazs/smoothscroll-for-websites/blob/master/SmoothScroll.js#L624 to

``` js
if (document.body.scrollTop != bodyScrollTop)
  (SCROLL_ROOT = document.body);
else if (document.documentElement.scrollTop != docElScrollTop)
  (SCROLL_ROOT = document.documentElement);
else
  (SCROLL_ROOT = document.body);
```

might be a reasonable fix, in my opinion.

**Comment by gblazex** [comment]
Thanks for debugging.

I believe this to be a Chrome bug.

When Zoom level <100% scrolling by 1px has no effect.

I fixed this in 1.4.1 by scrolling 3px instead of 1px
This works for Zoom levels above 50%
https://github.com/galambalazs/smoothscroll-for-websites/commit/a660055b46a06533979bb9f6ec2c35fdba59b77c

Should be fine for now.

In the long run we'll switch to the native document.scrollingElement anyway
https://dev.opera.com/articles/fixing-the-scrolltop-bug/

**Comment by gblazex** [comment]
reported here: https://code.google.com/p/chromium/issues/detail?id=560738

cc @bitwisecreative @pc035860

**Comment by pc035860** [comment]
Thanks for the quick update and release!
