### ISSUE TITLE
When keyboard support is enabled HOME key doesn't work

### ISSUE THREAD

**Issue by misternop** [galambalazs/smoothscroll-for-websites#60]
HOME key should scroll to top of the page but it doesn't work. Ctrl+HOME to skip smooth scrolling support works. Also if keyboard support is disabled then HOME works.

**Comment by Taapo** [comment]
Same problem here. Quite annoying when you are used to using this to scroll to the top ... :)

**Comment by kendoka15** [comment]
Same here :/

**Comment by kendoka15** [comment]
I made it work by commenting this part in sscr.js:
```
case key.home:
y = -overflowing.scrollTop;
break;
```
Then I loaded up the modified extension as a new extension in developer mode so that it doesn't show as corrupted with the help of this:
https://superuser.com/questions/848664/can-i-disable-chromes-extension-content-verification?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by gblazex** [comment]
fixed in latest version
